# Generated by Django 6.0.5 on 2026-06-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('vehiculo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
